CREATE TABLE CARGO (
	ID INT NOT NULL PRIMARY KEY,
	DESCRICAO VARCHAR(100)
);

CREATE TABLE ORGAO (
	ID INT NOT NULL PRIMARY KEY,
	DESCRICAO VARCHAR(100)
);

CREATE TABLE USUARIO (
	ID INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	CARGO_ID INT,
	ORGAO_ID INT,
	CONSTRAINT FK_USUARIO_CARGO_ID FOREIGN KEY(CARGO_ID) REFERENCES CARGO(ID),
	CONSTRAINT FK_USUARIO_ORGAO_ID FOREIGN KEY(ORGAO_ID) REFERENCES ORGAO(ID)
	
);

CREATE TABLE SISTEMA (
	ID INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL
);

CREATE TABLE USUARIOSISTEMA (
	SISTEMA_ID INT NOT NULL,
	USUARIO_ID INT NOT NULL,
	CONSTRAINT UK_USUARIOSISTEMA UNIQUE (SISTEMA_ID, USUARIO_ID),
	CONSTRAINT FK_USUARIOSISTEMA_SISTEMA_ID FOREIGN KEY(SISTEMA_ID) REFERENCES SISTEMA(ID),
	CONSTRAINT FK_USUARIOSISTEMA_USUARIO_ID FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(ID)
);
