-- CARGOS
INSERT INTO CARGO
SELECT *
FROM (
	SELECT 1 ID, 'DESENVOLVEDOR' DESCRICAO
	UNION
	SELECT 2 ID, 'ANALISTA DE SISTEMAS' DESCRICAO
	UNION
	SELECT 3 ID, 'ANALISTA DE REQUISITOS' DESCRICAO
	UNION
	SELECT 4 ID, 'ARQUITE DE SOFTWARE' DESCRICAO
	UNION
	SELECT 5 ID, 'GERENTE DE PROJETOS' DESCRICAO
) CARGOS
WHERE
	NOT EXISTS (SELECT 
					1 
				FROM 
					CARGO 
				WHERE 
					DESCRICAO = CARGOS.DESCRICAO)
					

-- ORGAOS
INSERT INTO ORGAO
SELECT *
FROM (
	SELECT 1 ID, 'SECRETARIA A' DESCRICAO
	UNION
	SELECT 2 ID, 'SECRETARIA B' DESCRICAO
	UNION
	SELECT 3 ID, 'SECRETARIA C' DESCRICAO
) ORGAOS
WHERE
	NOT EXISTS (SELECT 
					1 
				FROM 
					ORGAO 
				WHERE 
					DESCRICAO = ORGAOS.DESCRICAO)

-- SISTEMAS
INSERT INTO SISTEMA
SELECT *
FROM (
	SELECT 1 ID, 'SISTEMA PRIVADO' NOME
	UNION
	SELECT 2 ID, 'SISTEMA PUBLICO' NOME
	UNION
	SELECT 3 ID, 'SISTEMA GERAL' NOME
) SISTEMAS
WHERE
	NOT EXISTS (SELECT 
					1 
				FROM 
					SISTEMA 
				WHERE 
					NOME = SISTEMAS.NOME)
						

-- USUARIOS
INSERT INTO Usuario(ID, NOME, CPF, CARGO_ID, ORGAO_ID) VALUES (1, 'JAIR MESSIAS', '00011122299', 5, 1);
INSERT INTO Usuario(ID, NOME, CPF, CARGO_ID, ORGAO_ID) VALUES (2, 'DILMA', '00011133399', 1, 2);
INSERT INTO Usuario(ID, NOME, CPF, CARGO_ID, ORGAO_ID) VALUES (3, 'LULA', '00011144499', 4, 2);
INSERT INTO Usuario(ID, NOME, CPF, CARGO_ID, ORGAO_ID) VALUES (4, 'ITAMAR FRANCO', '00011155599', 3, 3);
INSERT INTO Usuario(ID, NOME, CPF, CARGO_ID, ORGAO_ID) VALUES (5, 'FERNANDO COLLOR', '00011166699', 2, 1);
INSERT INTO Usuario(ID, NOME, CPF, CARGO_ID, ORGAO_ID) VALUES (6, 'SARNEY', '00011177799', 3, 3);


-- USUARIOSISTEMA
-- Sistema publico(usuários)
INSERT INTO USUARIOSISTEMA (SISTEMA_ID, USUARIO_ID) VALUES (1,1);
INSERT INTO USUARIOSISTEMA (SISTEMA_ID, USUARIO_ID) VALUES (1,2);
INSERT INTO USUARIOSISTEMA (SISTEMA_ID, USUARIO_ID) VALUES (1,3);
INSERT INTO USUARIOSISTEMA (SISTEMA_ID, USUARIO_ID) VALUES (1,4);
INSERT INTO USUARIOSISTEMA (SISTEMA_ID, USUARIO_ID) VALUES (1,5);
INSERT INTO USUARIOSISTEMA (SISTEMA_ID, USUARIO_ID) VALUES (1,6);

-- Sistema privado(usuários)
INSERT INTO USUARIOSISTEMA (SISTEMA_ID, USUARIO_ID) VALUES (2,1);
INSERT INTO USUARIOSISTEMA (SISTEMA_ID, USUARIO_ID) VALUES (2,2);
INSERT INTO USUARIOSISTEMA (SISTEMA_ID, USUARIO_ID) VALUES (2,3);
INSERT INTO USUARIOSISTEMA (SISTEMA_ID, USUARIO_ID) VALUES (2,4);
INSERT INTO USUARIOSISTEMA (SISTEMA_ID, USUARIO_ID) VALUES (2,5);
INSERT INTO USUARIOSISTEMA (SISTEMA_ID, USUARIO_ID) VALUES (2,6);